from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def test_custom_frequency_draft_survives_heartbeat_until_explicit_apply() -> None:
    environment = dict(os.environ)
    environment.update(
        {
            "QT_QPA_PLATFORM": "offscreen",
            "QSG_RHI_BACKEND": "software",
            "PYTHONUTF8": "1",
        }
    )
    completed = subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "verify_companion_frequency_draft.py"),
        ],
        cwd=PROJECT_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=40,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        check=False,
    )
    assert completed.returncode == 0, completed.stdout + "\n" + completed.stderr
    report = json.loads(completed.stdout.strip().splitlines()[-1])
    assert report == {
        "passed": True,
        "zeroMix": {
            "interestSlider": 0,
            "sceneSlider": 0,
            "interestPreference": 0,
            "scenePreference": 0,
        },
        "afterExternalChange": {
            "draftMode": "quiet",
            "baselineMode": "quiet",
            "controlMode": "quiet",
            "dirty": False,
            "backendMode": "quiet",
        },
        "typedBeforeCommit": {
            "text": "222",
            "value": 25,
            "draft": 25,
            "dirty": True,
            "editing": True,
        },
        "duringEdit": {
            "draftMode": "custom",
            "text": "222",
            "minutes": 25,
            "dirty": True,
            "editing": True,
            "heartbeatSyncPending": False,
            "backendMode": "lively",
        },
        "afterBoundaryCommit": {
            "minutesText": "180",
            "minutes": 180,
            "minutesDraft": 180,
            "dailyText": "1",
            "daily": 1,
            "dailyDraft": 1,
            "dirty": True,
        },
        "afterRestore": {
            "draftMode": "lively",
            "baselineMode": "lively",
            "controlMode": "lively",
            "minutes": 25,
            "daily": 12,
            "dirty": False,
            "backendMode": "lively",
        },
        "incrementalTyping": [
            {"text": "3", "value": 25, "draft": 25, "editing": True},
            {"text": "37", "value": 25, "draft": 25, "editing": True},
        ],
        "beforeDirectApply": {
            "text": "9",
            "value": 12,
            "draft": 12,
            "activeFocus": True,
            "editing": True,
        },
        "afterApply": {
            "frequency": "custom",
            "minimumMinutes": 37,
            "dailyLimit": 9,
        },
        "afterApplyDraft": {
            "draftMode": "custom",
            "baselineMode": "custom",
            "minutes": 37,
            "daily": 9,
            "dirty": False,
        },
        "afterRestart": {
            "frequency": "custom",
            "minimumMinutes": 37,
            "dailyLimit": 9,
            "customMinimumMinutes": 37,
            "customDailyLimit": 9,
        },
        "beforeSettingsClose": {
            "draftMode": "custom",
            "dirty": False,
            "editing": True,
            "pending": True,
            "backendMode": "quiet",
        },
        "afterSettingsClose": {
            "draftMode": "quiet",
            "baselineMode": "quiet",
            "dirty": False,
            "editing": False,
            "pending": False,
            "backendMode": "quiet",
        },
        "dirtyAfterClose": {
            "text": "44",
            "dirty": True,
            "editing": False,
            "mode": "custom",
        },
        "dirtyAfterReopen": {
            "text": "44",
            "dirty": True,
            "mode": "custom",
        },
        "restoredAfterDirtyClose": {
            "draftMode": "quiet",
            "controlMode": "quiet",
            "minutes": 37,
            "daily": 9,
            "dirty": False,
            "backendMode": "quiet",
        },
        "afterDirectBoundaryApply": {
            "frequency": "custom",
            "minutes": 5,
            "daily": 4,
            "minutesText": "5",
            "dailyText": "4",
            "dirty": False,
        },
        "afterFailedPreset": {
            "draftMode": "custom",
            "controlMode": "custom",
            "dirty": False,
            "error": "保存失败，已恢复上一次设置",
            "backendMode": "custom",
            "backendMinutes": 5,
            "backendDaily": 4,
        },
        "afterFailedCustom": {
            "draftMode": "custom",
            "minutes": 33,
            "dailyText": "8",
            "daily": 8,
            "dirty": True,
            "error": "保存失败，修改仍保留；可以重试或恢复已保存",
            "backendMode": "custom",
            "backendMinutes": 5,
            "backendDaily": 4,
        },
        "afterFailedCustomRestore": {
            "draftMode": "custom",
            "minutes": 5,
            "daily": 4,
            "dirty": False,
            "error": "",
        },
        "afterNonFrequencyPreference": {
            "draftMode": "custom",
            "minutes": 41,
            "dailyText": "7",
            "dirty": True,
            "conflict": False,
            "pending": False,
            "backendMode": "custom",
            "interestWeight": 61,
        },
        "afterExternalConflict": {
            "draftMode": "custom",
            "minutes": 41,
            "dailyText": "7",
            "dirty": True,
            "conflict": True,
            "pending": True,
            "backendMode": "quiet",
            "noticeVisible": True,
            "restoreText": "恢复最新",
            "forceVisible": True,
            "forceEnabled": True,
        },
        "afterBlockedApply": {
            "draftMode": "custom",
            "minutes": 41,
            "dailyText": "7",
            "dirty": True,
            "conflict": True,
            "backendMode": "quiet",
            "backendMinutes": 45,
            "backendDaily": 6,
            "error": "未应用：频率已在其他位置更新；请恢复最新设置，或选择“仍然应用”确认覆盖",
        },
        "afterConflictRestore": {
            "draftMode": "quiet",
            "baselineMode": "quiet",
            "minutes": 5,
            "daily": 4,
            "dirty": False,
            "conflict": False,
            "pending": False,
            "backendMode": "quiet",
            "restoreText": "恢复已保存",
        },
        "afterForcedApply": {
            "draftMode": "custom",
            "baselineMode": "custom",
            "minutes": 42,
            "daily": 8,
            "dirty": False,
            "conflict": False,
            "pending": False,
            "backendMode": "custom",
            "backendMinutes": 42,
            "backendDaily": 8,
            "error": "",
        },
        "afterExternalBeforeTyping": {
            "dirty": False,
            "editing": True,
            "pending": True,
            "conflict": False,
            "backendMode": "quiet",
        },
        "afterLateTyping": {
            "text": "43",
            "dirty": True,
            "pending": True,
            "conflict": True,
            "backendMode": "quiet",
        },
        "afterLateTypingBlockedApply": {
            "draftText": "43",
            "conflict": True,
            "backendMode": "quiet",
            "backendMinutes": 45,
            "backendDaily": 6,
            "noticeVisible": True,
            "forceVisible": True,
            "sameError": True,
        },
        "interestDraftProtection": {
            "typed": "draft,topic",
            "afterHeartbeat": "draft,topic",
            "afterUnrelatedPreference": "draft,topic",
            "dirtyAfterUnrelatedPreference": True,
            "mixAfterUnrelatedPreference": [62, 38, 31],
            "savedInterests": ["draft", "topic"],
            "dirtyAfterCommit": False,
            "canonicalAfterCommit": True,
            "cleanExternalRefill": True,
            "savedAfterExternalRefill": ["external", "clean"],
        },
        "screenReopenCancellation": {
            "buttonEnabled": True,
            "afterClick": {
                "chatOpen": False,
                "visible": False,
                "timerRunning": True,
            },
            "afterReopen": {
                "chatOpen": True,
                "visible": True,
                "timerRunning": False,
            },
            "requestCallsAfterDeadline": 0,
            "feedbackUnchanged": True,
        },
    }
